### ISSUE TITLE
Unable to use the plugin on linux

### ISSUE THREAD

**Issue by noREAVER** [landinig/IJ-Colour_Deconvolution2#1]
Hi
I'm trying to use the plugin on linux but fiji cannot open it. It throws an error ar startup. On windows it works but there is something wrong with the file when trying to open it directly.

**Comment by landinig** [comment]
Hi can you explain how you installed it?

**Comment by landinig** [comment]
There is a Fiji update site, described here, in the "Installation" section:
https://blog.bham.ac.uk/intellimic/g-landini-software/colour-deconvolution-2/

**Comment by noREAVER** [comment]
Hi
Same like for windows. Downloaded/copied the jar file into plugins
directory.
But when I open ImageJ app in Linux(Fedora30) I get this error and the
plugin is not loaded.
Fiji.app/plugins/colour_deconvolution2.jar: java.util.zip.ZipException:
error in opening zip file
I just noticed/tested now the update site method and that works.

Best regards.

**Comment by landinig** [comment]
I cannot reproduce the error in either ImageJ or Fiji under linux. I suspect that your jar file was corrupted during download.
Copying the jar file to the plugins folder works fine in ImageJ and Fiji (note that according to the error you posted you are using Fiji, not ImageJ).
Installation in Fiji should best be done using the update site to get the automatic updates when available. 
Happy to hear you succeeded installing it that way.
